-- Source: https://www.coursera.org/learn/python-databases/lecture/jdLhw/15-5-representing-a-data-model-in-tables

-- The database is located in the databases/tracksdb.db and was created using DB Browser for SQLite

-- CREATING TABLES
-- ---------------

CREATE TABLE Artists (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    name TEXT
);

CREATE TABLE Genres (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    name TEXT
);

CREATE TABLE Albums (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    title TEXT,
    artist_id INTEGER
);

CREATE TABLE Tracks (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    title TEXT,
    rating INTEGER,
    length INTEGER,
    count INTEGER,
    album_id INTEGER,
    genre_id INTEGER
);

-- INSERTING DATA
-- --------------

-- We do not specify the 'id' field because it is auto-generated by the database
INSERT INTO Artists (name) VALUES ('Led Zeppelin');
INSERT INTO Artists (name) VALUES ('AC/DC');

INSERT INTO Genres (name) VALUES ('Rock');
INSERT INTO Genres (name) VALUES ('Metal');

-- Specifying foreign keys
INSERT INTO Albums (title, artist_id) VALUES ('Who Made Who', 2); -- artist_id = 2 corresponds to AC/DC
INSERT INTO Albums (title, artist_id) VALUES ('IV', 1); -- artist_id = 1 corresponds to Led Zeppelin

INSERT INTO Tracks (title, rating, length, count, album_id, genre_id) VALUES ('Black Dog', 5, 297, 0, 2, 1);
INSERT INTO Tracks (title, rating, length, count, album_id, genre_id) VALUES ('Stairway', 5, 482, 0, 2, 1);
INSERT INTO Tracks (title, rating, length, count, album_id, genre_id) VALUES ('About to Rock', 5, 313, 0, 1, 2);
INSERT INTO Tracks (title, rating, length, count, album_id, genre_id) VALUES ('Who Made Who', 5, 207, 0, 1, 2);